networks:
  my_network:
    name: 'my_network'

services:
  postgres:
    container_name: 'postgres_container'
    image: postgres:16.3
    networks:
      - my_network
    volumes:
      - ./BD.txt:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=udp_apuntes_en_linea
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: 'flask_app'
    networks:
      - my_network
    depends_on:
      - postgres
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
